version: 2.1

orbs:
  python: circleci/python@1.1.0
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  build-and-test:
    docker: 
      - image: dbtmsft/msodbc_py:0.5
    executor: python/default 
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - azure-cli/install
      - azure-cli/login-with-service-principal:
          azure-sp: DBT_AZURE_SP_NAME
          azure-sp-password: DBT_AZURE_SP_SECRET
          azure-sp-tenant: DBT_AZURE_TENANT
      - run:
          name: resume Synapse pool/db
          command: |
            state=$(az synapse sql pool show --name $DBT_SYNAPSE_DB --resource-group dbt-msft --workspace-name $DBT_SYNAPSE_SERVER --query "status")
            if [ "$state" = "Paused" ]; then
              echo "Resuming pool!"
              az synapse sql pool resume --name $DBT_SYNAPSE_DB --resource-group dbt-msft --workspace-name $DBT_SYNAPSE_SERVER
              echo "waiting to be resumed"
              az synapse sql pool wait --sql-pool-name $DBT_SYNAPSE_DB --resource-group dbt-msft --workspace-name $DBT_SYNAPSE_SERVER --custom "state==Online" 
              echo "Pool is now resumed!"
            fi
      - run:
          name: Test
          command: tox -e integration-synapse
      - run:
          name: pause Synapse pool/db
          command: |
            state=$(az synapse sql pool show --name $DBT_SYNAPSE_DB --resource-group dbt-msft --workspace-name $DBT_SYNAPSE_SERVER --query "status")
            if [ "$state" = "Online" ]; then
              echo "Pausing pool!"
              az synapse sql pool pause --name $DBT_SYNAPSE_DB --resource-group dbt-msft --workspace-name $DBT_SYNAPSE_SERVER
              echo "waiting until paused"
              az synapse sql pool wait --sql-pool-name $DBT_SYNAPSE_DB --resource-group dbt-msft --workspace-name $DBT_SYNAPSE_SERVER --custom "state==Paused" 
              echo "Pool is now paused!"
            fi

          when: always


workflows:
  main:
    jobs:
      - build-and-test:
          context:
            - DBT_SYNAPSE_PROFILE
