version: 2.1

orbs:
  python: circleci/python@2.0.3
  azure-cli: circleci/azure-cli@1.2.2

jobs:
  build-and-test:
    docker: &msodbc_py
      - image: &docker_image ghcr.io/dbt-msft/dbt-sqlserver:latest
    steps:
      - checkout
      - python/install-packages: &install_dev
          pkg-manager: pip
          pip-dependency-file: dev_requirements.txt
      - run: &install-dbt-synapse
          name: "install dbt-synapse"
          command: |
            pip install .
      - azure-cli/install
      - azure-cli/login-with-service-principal:
          azure-sp: DBT_AZURE_SP_NAME
          azure-sp-password: DBT_AZURE_SP_SECRET
          azure-sp-tenant: DBT_AZURE_TENANT
      - run:
          name: resume Synapse pool/db
          command: python .circleci/synapse.py resume
      - run:
          name: Test
          command: tox -e integration-synapse
      - run:
          name: pause Synapse pool/db
          command: python .circleci/synapse.py pause
          when: always

  release-new-version:
    docker: *msodbc_py
    steps:
      - checkout
      - python/install-packages: *install_dev
      - run: *install-dbt-synapse
      - run:
          name: verify git tag vs. version
          command: python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_DBT_SYNAPSE" >> ~/.pypirc
      - run:
          name: build and publish package
          command: |
            python setup.py sdist bdist_wheel
            twine upload dist/*


workflows:
  main:
    jobs:
      - build-and-test:
          context:
            - DBT_SYNAPSE_PROFILE
          filters: &untagged-filters
            tags:
              only: /.*/
      - release-new-version:
          context:
            - DBT_SYNAPSE_PROFILE
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - build-and-test
