---
name: Integration tests on Azure
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request_target:
    types: [labeled]

jobs:
  integration-tests-azure:
    name: Integration tests on Azure
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.ref_name == 'master'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python_version: ["3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-sqlserver:${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -e . && pip install -r dev_requirements.txt

      - name: Resume server
        env:
          DBT_SYNAPSE_SERVER: ${{ secrets.DBT_SYNAPSE_SERVER }}
          DBT_SYNAPSE_DB: ${{ secrets.DBT_SYNAPSE_DB }}
          AZURE_CLIENT_ID: ${{ secrets.DBT_AZURE_SP_NAME }}
          AZURE_CLIENT_SECRET: ${{ secrets.DBT_AZURE_SP_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.DBT_AZURE_TENANT }}
          DBT_AZURE_RESOURCE_GROUP_NAME: ${{ secrets.DBT_AZURE_RESOURCE_GROUP_NAME }}
          DBT_AZURE_SUBSCRIPTION_ID: ${{ secrets.DBT_AZURE_SUBSCRIPTION_ID }}
        run: python .github/synapse.py resume

      - name: Run functional tests
        env:
          DBT_SYNAPSE_SERVER: ${{ secrets.DBT_SYNAPSE_SERVER }}
          DBT_SYNAPSE_DB: ${{ secrets.DBT_SYNAPSE_DB }}
          AZURE_CLIENT_ID: ${{ secrets.DBT_AZURE_SP_NAME }}
          AZURE_CLIENT_SECRET: ${{ secrets.DBT_AZURE_SP_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.DBT_AZURE_TENANT }}
        run: |
          RAW_TOXENV="py${{ matrix.python_version }}-azure"
          TOXENV=$(echo $RAW_TOXENV | sed 's/\.//')
          tox -e "$TOXENV" -- tests/functional --profile "ci_azure_auto"

      - name: Pause server
        env:
          DBT_SYNAPSE_SERVER: ${{ secrets.DBT_SYNAPSE_SERVER }}
          DBT_SYNAPSE_DB: ${{ secrets.DBT_SYNAPSE_DB }}
          AZURE_CLIENT_ID: ${{ secrets.DBT_AZURE_SP_NAME }}
          AZURE_CLIENT_SECRET: ${{ secrets.DBT_AZURE_SP_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.DBT_AZURE_TENANT }}
          DBT_AZURE_RESOURCE_GROUP_NAME: ${{ secrets.DBT_AZURE_RESOURCE_GROUP_NAME }}
          DBT_AZURE_SUBSCRIPTION_ID: ${{ secrets.DBT_AZURE_SUBSCRIPTION_ID }}
        run: python .github/synapse.py resume
        if: always()
